---
title: "Light logger"
author: "Areej Hassan"
course: "Thesis"
---


```{r load-packages, include=FALSE}
#libraries to be loaded
library(LightLogR)
#these packages are needed for the examples as shown below.
library(flextable)
library(dplyr)
library(ggplot2)
library(lubridate)
library(gtsummary)
```

#### Load the dataset

```{r}
path <- "D:/Thesis/101/files/"
files <- list.files(path, full.names = TRUE)
#show how many files are listes
length(files)

tz <- "Europe/Berlin"
pattern <- "^(\\d{3})"
data <- import$ActLumus(files, tz = tz, auto.id = pattern, dst_adjustment = TRUE, 
                  auto.plot = FALSE, silent = TRUE)

```

#### Visualize the dataset

```{r}
data <- 
  data %>% 
  filter_Datetime_multiple(list(
      list(only_Id = quote(Id == 101))
    ), length = "1 year", length_from_start = FALSE)

data %>% gg_overview()

```

#### Extract only one day

```{r}
data$date <- as.Date(data$Datetime,tz=tz)
data_Id101 <- data %>% filter(Id == 101 & date == "2024-07-11")
data_Id101 %>% gg_day()

```

#### Time above threshold

```{r echo=TRUE, message=FALSE, warning=FALSE}
duration_above_threshold(
  Light.vector = data_Id101$MEDI,
  Time.vector = data_Id101$Datetime,
  threshold = 20
)

```

#### Brightest 10 hours of the day

```{r echo=TRUE, message=FALSE, warning=FALSE}
brightest101 = bright_dark_period(
  Light.vector = data_Id101$MEDI,
  Time.vector = data_Id101$Datetime,
  as.df = TRUE
)
brightest101
```

#### Darkest 10 hours of the day

```{r echo=TRUE, message=FALSE, warning=FALSE}
M10_wrong <- 
bright_dark_period(
  Light.vector = data_Id101$MEDI,
  Time.vector = data_Id101$Datetime,
  as.df = TRUE,
  period = "darkest",
  timespan = "10 hours"
)
M10_wrong
Onset <- M10_wrong$darkest_10h_onset
Offset <- M10_wrong$darkest_10h_offset

data_Id101 %>% 
  gg_day(aes_col = Datetime >= Onset & Datetime <= Offset) +
  guides(color = "none")
```

#### Darkest 10 hours of the day with loop

```{r echo=TRUE, message=FALSE, warning=FALSE}
M10 <- 
bright_dark_period(
  Light.vector = data_Id101$MEDI,
  Time.vector = data_Id101$Datetime,
  as.df = TRUE,
  period = "darkest",
  timespan = "10 hours",
  loop = TRUE
)
M10
Onset <- M10$darkest_10h_onset
Offset <- M10$darkest_10h_offset

data_Id101 %>% 
  gg_day(aes_col = Datetime >= Onset | Datetime <= Offset) +
  guides(color = "none")
```


#### Interdaily Stability

```{r echo=TRUE, message=FALSE, warning=FALSE}
IS_Id101 = data %>% 
  summarize(
    IS = interdaily_stability(
      Light.vector = MEDI,
      Datetime.vector = Datetime
    )
  )
IS_Id101
```

#### TAT_250

```{r echo=TRUE, message=FALSE, warning=FALSE}
TAT250_Id101 = data %>% 
  summarize(
    TAT_250 = duration_above_threshold(
      Light.vector = MEDI,
      Time.vector = Datetime,
      threshold = 250
    )
  )
TAT250_Id101
```

#### TAT_250

```{r echo=TRUE, message=FALSE, warning=FALSE}
#create a new column in the data set with the weekday
data$wDay <- wday(data$Datetime, label = TRUE, week_start = 1)

#group the data and calculate the metrics
TAT_250_wday_Id101 <- 
data %>% 
  group_by(wDay, .add = TRUE) %>% 
  summarize(
    TAT_250 = duration_above_threshold(
      Light.vector = MEDI,
      Time.vector = Datetime,
      threshold = 250
    ), .groups = "drop_last"
  )

TAT_250_wday_Id101
```

#### metric_statistics

```{r echo=TRUE, message=FALSE, warning=FALSE}
#styling formula for time
style_time <- function(x, format = "%H:%M"){
  x %>% as.numeric() %>%  hms::as_hms() %>% as.POSIXlt() %>% format(format)
}

#Table output
TAT_250_wday_Id101 %>% 
  tbl_summary(
    by = Id,
    include = -wDay,
    statistic = list(all_continuous() ~ "{mean} ({sd})"),
    digits = list(TAT_250 ~ style_time),
    label = list(TAT_250 = "Time above 250 lx mel EDI")
              )
```
